[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos_ocp_rss_plugin"
dynamic = ["version"]
description = "OCP rss feed stream extractor plugin"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "JarbasAi", email = "jarbasai@mailfence.com"}
]
keywords = ["ovos", "ocp", "plugin"]
dependencies = [
    "ovos-plugin-manager>=2.1.0,<3.0.0",
    "feedparser"
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-ocp-rss-plugin"

[project.entry-points."opm.ocp.extractor"]
"ovos-ocp-rss-plugin" = "ovos_ocp_rss_plugin:OCPRSSFeedExtractor"

[project.entry-points."opm.ocp.extractor.config"]
"ovos-ocp-rss-plugin.config" = "ovos_ocp_rss_plugin:OCPRSSFeedExtractorConfig"

[tool.setuptools.dynamic]
version = {attr = "ovos_ocp_rss_plugin.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ovos_ocp_rss_plugin*"]

[tool.setuptools.package-data]
ovos_ocp_rss_plugin = [
    "*.json",
]
